tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "sanemat/font"
brew "coreutils"
brew "asdf"
brew "curl"
brew "ghq"
brew "git"
brew "gnupg"
brew "htop"
brew "tig"
brew "vim"
brew "zsh"
brew "sanemat/font/ricty", args: ["with-powerline"]
cask "dynamodb-local"
cask "google-cloud-sdk"
